#!/bin/bash -eu

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

script_dir=$(dirname $0)
dist_dir=$(realpath $script_dir/../dist)

echo "Determining version number..."
current_version=`npm view @implydata/web-console@latest version`
next_version=`$script_dir/next-version-number.js $current_version`

echo "Staging 'dist' dir for publishing..."
cp LICENSE-IMPLY dist/LICENSE
$script_dir/merge-package-json.js $next_version

echo "Publishing @implydata/web-console@$next_version..."
npm publish $dist_dir $@

echo "Done! Have a good day."

