name: Apache Druid Community PRs

on:
  schedule:
    - cron:  '0 */6 * * *' #Every 6 hours

jobs:
  communityPRs:
    runs-on: imply-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create jira tickets for community PRs
        env:
          JIRA_BASE_URL: "https://implydata.atlassian.net"
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_GITHUB_ACTION }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests jira PyGithub
          echo "PYTHON_OUTPUT=$(python3 ${GITHUB_WORKSPACE}/.github/create_jira_ticket_for_untracked_community_prs.py)" >> $GITHUB_ENV
          echo ${{ env.PYTHON_OUTPUT }}
      - name: Slack Notification for job failed
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_USERNAME: "barista bob"
          SLACK_ICON_EMOJI: ":barista:"
          SLACK_MESSAGE: "Community PR monitoring failed with the following error - ```${{ env.PYTHON_OUTPUT }}```"
          SLACK_TITLE: "[FAILED] Error while creating jira for community PRs"
          SLACK_COLOR: "danger"
          SLACK_CHANNEL: espresso-machine
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
