name: Apache Druid Community PRs

on:
  schedule:
    - cron:  '0 */2 * * *' #Every 2 hours

jobs:
  communityPRs:
    runs-on: ubuntu-latest
    steps:
      - name: Create jira tickets for community PRs
        env:
          JIRA_BASE_URL: "https://implydata.atlassian.net"
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_GITHUB_ACTION }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests jira github
          output=$(python3 ${GITHUB_WORKSPACE}/.github/create_jira_ticket_for_untracked_community_prs.py)
          echo "::set-output name=tickets::$output"

      - name: Slack Notification for job failed
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_USERNAME: "barista bob"
          SLACK_ICON_EMOJI: ":barista:"
          SLACK_MESSAGE: "The following tickets were created for community PR tracking - ```${{ steps.step1.outputs.tickets }}```"
          SLACK_TITLE: "Community PR author in apache druid"
          SLACK_CHANNEL: espresso-machine
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
