name: Checksum verification

on:
  # Run at 11 PM every day.
  schedule:
    - cron: "0 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checksumVerification:
    runs-on: imply-ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checksum: [ {script: run-druid, checksum: 070e9573bcb2980596156121b851d5b8de848dff},
                    {script: run-java, checksum: adcff92ea4f9626ed48c5b56a582510830f6b9fc},
                    {script: verify-java, checksum: d3a1c1dd6c997dfb68d6756fd165b73707cf5b0e},
                    {script: run-zk, checksum: 6a995c9279ebe3015598891c3896820f33a97d8f} ]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: implydata/druid
          ref: master
          fetch-depth: 0
          token: ${{ secrets.PAT_FOR_GITHUB_ACTION}}

      - name: Verify Checksum
        run: |
          ACTUAL_CHECKSUM=$(shasum examples/bin/${{ matrix.checksum.script }} | awk '{print $1}')
          if [[ $ACTUAL_CHECKSUM == ${{ matrix.checksum.checksum }} ]]; then
            echo "${{ matrix.checksum.script }} checksum verification was successful"
          else
            echo "OUTPUT<<EOF" >> $GITHUB_ENV
            echo "Expected Checksum - ${{ matrix.checksum.checksum }}" >> $GITHUB_ENV
            echo "Actual checksum - $ACTUAL_CHECKSUM" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            exit 1
          fi
        shell: bash

      - name: Slack Notification for job failed
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_USERNAME: "barista bob"
          SLACK_ICON_EMOJI: ":barista:"
          SLACK_MESSAGE: "```${{ env.OUTPUT }}```"
          SLACK_TITLE: "[FAILED] Checksum verification failed for ${{ matrix.checksum.script }} script in master branch"
          SLACK_COLOR: "danger"
          SLACK_CHANNEL: espresso-machine
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
