name: Pull Request on Master Branch Push
on:
  push:
    branches:
      - master
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: create-new-branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'master-for-merge-to-release'
      - name: checkout-to-new-branch
        uses: actions/checkout@v2
        with:
          repository: implydata/druid
          ref: master-for-merge-to-release
          fetch-depth: 0
      - name: rebase-new-branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase origin master
          git push --force
      - name: pull-request-action
        id: pull_request
        uses: vsoch/pull-request-action@1.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "master-for-merge-to-release"
          PULL_REQUEST_FROM_BRANCH: "master-for-merge-to-release" 
          PULL_REQUEST_BRANCH: "0.20.0-iap"
      - name: Print outputs
        env:
          pull_request_number_output: ${{ steps.pull_request.outputs.pull_request_number }}
          pull_request_url_output: ${{ steps.pull_request.outputs.pull_request_url }}
        run: |
          echo "Pull request number from output: ${pull_request_number_output}"
          echo "Pull request url from output: ${pull_request_url_output}"
          echo "Pull request number from environment: ${PULL_REQUEST_NUMBER}"
          echo "Pull request url from environment: ${PULL_REQUEST_URL}"
          echo "Another way to specify from output ${{ steps.pull_request.outputs.pull_request_number }}"
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_MESSAGE: "Pull request url: ${{ steps.pull_request.outputs.pull_request_url }} (If null, the PR already exists and can be accessed at https://github.com/implydata/druid/pulls)"
          SLACK_TITLE: Automatic Backport PR Created
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}