name: Update implydata/druid monthly with implydata/druid master
on:
  schedule:
    - cron:  '0 */1 * * *' #Every 1 hours
jobs:
  updateMonthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: implydata/druid
          ref: monthly
          fetch-depth: 0
          token: ${{ secrets.PAT_FOR_GITHUB_ACTION}}
      - name: rebase implydata/druid monthly with implydata/druid master
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout monthly
          echo "PREV_MONTHLY_COMMIT=$(git log monthly -n 1 --pretty=format:'%h' --grep='into monthly' -- ${{ env.FILE }})" >> $GITHUB_ENV
          git merge origin/master
          git push
      - name: setup jdk 8
        if: ${{ success() }}
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: create jira tickets for apache/druid PR merged
        if: ${{ success() }}
        run: |
          FIX_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout| cut -d'.' -f1,2)
          chmod +x "${GITHUB_WORKSPACE}/.github/create_jira_ticket.sh"
          GIT_TOKEN=${{ secrets.JIRA_USER }}":"${{ secrets.JIRA_TOKEN }}
          .github/script.sh -d ${GITHUB_WORKSPACE} -c ${{ env.PREV_MONTHLY_COMMIT }} -j $GIT_TOKEN -f $FIX_VERSION
      - name: Files causing merge conflict
        if: ${{ failure() }}
        run: |
            echo "FILE=$(git diff --name-only --diff-filter=U |head -1)"  >> $GITHUB_ENV
            echo "MONTHLY_COMMIT=$(git log monthly -n 1 --pretty=format:'%h' -- ${{ env.FILE }})" >> $GITHUB_ENV
            echo "MONTHLY_COMMITER=$(git log monthly -n 1 --pretty=format:'%an' -- ${{ env.FILE }})" >> $GITHUB_ENV
            echo "MASTER_COMMIT=$(git log origin/master -n 1 --pretty=format:'%h' -- ${{ env.FILE }})" >> $GITHUB_ENV
            echo "MASTER_COMMITER=$(git log origin/master -n 1 --pretty=format:'%an' -- ${{ env.FILE }})" >> $GITHUB_ENV
      - name: Slack Notification for job failed
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_USERNAME: "barista bob"
          SLACK_ICON_EMOJI: ":barista:"
          SLACK_MESSAGE: "Automatic sync failed possibly due to merge conflicts. Manual merge required. `${{ env.FILE }}` caused the conflict and was last updated in `monthly` by ${{ env.MONTHLY_COMMITER }} with commit [${{ env.MONTHLY_COMMIT }}](https://github.com/implydata/druid/commit/${{ env.MONTHLY_COMMIT }}) and in `master` by ${{ env.MASTER_COMMITER }} with commit [${{ env.MASTER_COMMIT }}](https://github.com/implydata/druid/commit/${{ env.MASTER_COMMIT }}). See https://implydata.atlassian.net/wiki/spaces/ENG/pages/1461060101/Automatic+backport+PR+for+Druid+repo#Merge-conflicts for tips on resolving merge conflicts"
          SLACK_TITLE: "[FAILED] Update implydata/druid#monthly with implydata/druid#master"
          SLACK_COLOR: "danger"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
